https://colab.research.google.com/notebooks/welcome.ipynb

Deep Learning Drizzle
https://github.com/kmario23/deep-learning-drizzle?fbclid=IwAR3TA53-xn0k8b8NDD9OSJA6xF20iya4dd73vIOy4tzmh-NmTAMZitEcIo0

Browse state-of-the-art
https://paperswithcode.com/sota?fbclid=IwAR3Ngsdmay4PoSkdM_2oK3cf_HZeZcXZ3CmmDxUrz9zdjCgBiu9nsQJt9HU

권세혁(權世赫 Sehyug Kwon), 한남대학교 비즈니스통계학과 교수
http://wolfpack.hannam.ac.kr

http://www.dodomira.com/2016/03/06/데이터를-분석할-때-자주-하는-실수들/

회귀분석 https://ordo.tistory.com/23
상관분석 https://ordo.tistory.com/21
